import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MedusaProvider } from "medusa-react";
import { QueryClient } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MedusaProvider
        queryClientProviderProps={{ client: queryClient }}
        baseUrl="http://localhost:9000"
      >
        <body className={inter.className}>{children}</body>
      </MedusaProvider>
    </html>
  );
}
