import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MedusaWrapper } from "@/utils/wrappers/medusaWrapper";
import Navigation from "@/components/navigation";
import { Footer } from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navigation />
      <MedusaWrapper>
        <body className={inter.className}>{children}</body>
      </MedusaWrapper>
      <Footer />
    </html>
  );
}
